base_url: https://glowing-train-pjqg4gx9v9w53r99w-8080.app.github.dev
dashboard_url: https://glowing-train-pjqg4gx9v9w53r99w-8080.app.github.dev/dashboard
smtp:
  host: smtp.gmail.com
  port: 465
  user: dadae5th@gmail.com
  pass: kptwwtdbavjgajly
  sender_name: 해야할일 알림
  sender_email: dadae5th@gmail.com
secret: gBckLh5s3CSP5VIu6TPi0f1aic6tofQ9EFgrcwf24W1Zl4B2
