name: Daily Email Reminder

on:
  schedule:
    # 매일 한국시간 오전 9시 (UTC 00:00 = KST 09:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  send-daily-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create environment file
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
        echo "SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}" >> .env
        echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
        echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env
        echo "SMTP_SENDER_NAME=${{ secrets.SMTP_SENDER_NAME }}" >> .env
        echo "SMTP_SENDER_EMAIL=${{ secrets.SMTP_SENDER_EMAIL }}" >> .env
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
        echo "DASHBOARD_URL=${{ secrets.DASHBOARD_URL }}" >> .env
        echo "SECRET=${{ secrets.SECRET }}" >> .env
        
    - name: Send daily emails
      run: |
        python send_digest_supabase.py
        
    - name: Log completion
      run: |
        echo "Daily email job completed at $(date)"
        echo "Email sending status: SUCCESS"
